spring:
  data:
    mongodb:
      auto-index-creation: true
      username: admin
      password: pass
      database: smart
      port: 27017
      host: localhost
      authentication-database: admin